server:
  port: 9999

spring:
  application:
    name: fangte-gateway

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://fangte-eureka:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 45000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 90000   #socket超时
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
