server:
  port: 3001

spring:
  application:
    name: fangte-zipkin
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

eureka:
  instance:
    prefer-ip-address: true
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://fangte-eureka:8761/eureka/

management:
  metrics:
    web:
      # 解决Zipkin报错IllegalArgumentException: Prometheus requires that all meters
      server:
        auto-time-requests: false

